"use strict";

const STORAGE={api:"jbGeminiApiKey",model:"jbGeminiModel",rules:"jbExamMakerRules"};
const DEFAULT_RULES={
  questionRules:`[문항 구성]\n- 2022 개정 교육과정 통합과학1·2 범위에서 출제한다.\n- 참고 문항의 개념과 자료 구조만 결합하고 문장, 상황, 수치를 그대로 복제하지 않는다.\n- 문제에 제시한 정보만으로 정답 하나가 확정되어야 한다.\n- 발문은 “이에 대한 설명으로 옳은 것만을 <보기>에서 있는 대로 고른 것은?” 등 평가원 문체로 작성한다.\n- 선택지는 ①, ②, ③, ④, ⑤를 사용하고 정답 번호와 ㄱ·ㄴ·ㄷ의 참·거짓 조합을 일치시킨다.\n\n[자료와 표기]\n- 표, 그래프, 그림은 본문만으로 대신 설명하지 말고 실제 완성된 자료로 제시한다.\n- 그래프와 그림은 흑백 평가원 스타일 SVG로 만들고 축, 단위, 눈금, 범례, A~C, (가)~(다)를 빠짐없이 표시한다.\n- 화학식의 원자 수는 아래첨자, 이온의 전하는 위첨자로 나타낸다. 예: H₂O, Ca²⁺, OH⁻\n- 물리량의 값과 단위를 띄어 쓴다. 예: 3 m/s, 20 N\n- 범위는 A ~ C처럼 물결표 앞뒤를 띄어 쓴다.\n- 임의의 원소 기호를 사용하면 “(단, A와 B는 임의의 원소 기호이다.)”처럼 조건을 밝힌다.`,
  explanationRules:`[해설 기본 형식]\n- 해설 첫 문단에서 미지 기호의 실제 대상을 먼저 확정한다. 예: “㉠은 산소(O), ㉡은 수소(H), ㉢은 헬륨(He)이다.”\n- 이후에는 “A(수소)는 원자가 전자가 1개이다.”처럼 기호와 실제 대상을 함께 적어 독자가 다시 대응하지 않게 한다.\n- 별도의 장황한 서론 없이 정답 판단에 필요한 근거부터 쓴다.\n- 옳은 보기는 “ㄱ. …”, “ㄷ. …”처럼 보기 기호별로 설명한다.\n- 틀린 보기는 “[오답 풀이] ㄴ. …” 형식으로 이어서 설명한다.\n- 한 보기의 설명은 원칙적으로 한 문단으로 쓰고 같은 내용을 반복하지 않는다.\n- 계산형은 식 → 값의 대입 → 계산 결과와 단위 순서로 쓴다.\n- 표나 그래프를 해석할 때는 어떤 구간·행·열·축을 근거로 판단했는지 명시한다.\n- 문제에 없는 조건이나 값을 해설에서 새로 만들지 않는다.\n- 원소가 처음 등장하면 한글명과 원소 기호를 함께 쓰고, 이후에도 혼동 가능성이 있으면 함께 쓴다.\n- 정답인 보기와 오답인 보기의 설명을 모두 작성한다.`,
  customRules:""
};
const state={db:[],types:[],references:[],result:null};
const $=id=>document.getElementById(id);

document.addEventListener("DOMContentLoaded",init);
async function init(){
  bindTabs();bindEvents();loadRules();loadApiSettings();
  try{const manifestResponse=await fetch("data/manifest.json",{cache:"no-cache"});if(!manifestResponse.ok)throw new Error(`HTTP ${manifestResponse.status}`);const manifest=await manifestResponse.json();const responses=await Promise.all(manifest.files.map(name=>fetch(`data/${name}`,{cache:"no-cache"})));if(responses.some(x=>!x.ok))throw new Error("문항 데이터 일부를 불러오지 못했습니다.");state.db=(await Promise.all(responses.map(x=>x.json()))).flat();state.types=[...new Set(state.db.map(x=>x.type).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"ko"));$("typeSelect").replaceChildren(new Option("유형을 선택하세요",""),...state.types.map(x=>new Option(`${x} (${state.db.filter(y=>y.type===x).length})`,x)));$("dataStatus").textContent=`통합과학 ${state.db.length.toLocaleString("ko-KR")}문항 준비됨`;}catch(e){$("dataStatus").textContent="DB 로딩 실패";alert(`문항 DB를 불러오지 못했습니다. ${e.message}`)}
}
function bindTabs(){document.querySelectorAll(".tab").forEach(btn=>btn.addEventListener("click",()=>openTab(btn.dataset.tab)))}
function openTab(name){document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x.dataset.tab===name));document.querySelectorAll(".panel").forEach(x=>x.classList.toggle("active",x.id===`${name}Panel`))}
function bindEvents(){
  $("apiButton").addEventListener("click",()=>$("apiDialog").showModal());$("saveApi").addEventListener("click",saveApiSettings);$("removeApi").addEventListener("click",removeApiSettings);
  $("saveRules").addEventListener("click",saveRules);$("resetRules").addEventListener("click",resetRules);
  $("typeSelect").addEventListener("change",drawReferences);$("formatSelect").addEventListener("change",drawReferences);$("referenceCount").addEventListener("change",drawReferences);$("normalOnly").addEventListener("change",drawReferences);$("drawReferences").addEventListener("click",drawReferences);
  $("generateButton").addEventListener("click",generate);$("copyQuestion").addEventListener("click",()=>copyResult(false));$("copyAll").addEventListener("click",()=>copyResult(true));
}
function loadRules(){const raw=JSON.parse(localStorage.getItem(STORAGE.rules)||"null"),saved=raw?.questionRules?raw:DEFAULT_RULES;Object.keys(DEFAULT_RULES).forEach(k=>$(k).value=saved[k]??DEFAULT_RULES[k])}
function collectRules(){return Object.fromEntries(Object.keys(DEFAULT_RULES).map(k=>[k,$(k).value.trim()]))}
function saveRules(){localStorage.setItem(STORAGE.rules,JSON.stringify(collectRules()));flash($("saveRules"),"저장됨")}
function resetRules(){if(!confirm("입력한 규칙을 기본값으로 되돌릴까요?"))return;Object.keys(DEFAULT_RULES).forEach(k=>$(k).value=DEFAULT_RULES[k]);saveRules()}
function loadApiSettings(){$("apiKey").value=localStorage.getItem(STORAGE.api)||"";$("modelName").value=localStorage.getItem(STORAGE.model)||"gemini-3.5-flash";updateApiButton()}
function saveApiSettings(){const key=$("apiKey").value.trim(),model=$("modelName").value.trim();if(!key||!model){alert("API 키와 모델명을 입력해 주세요.");return}localStorage.setItem(STORAGE.api,key);localStorage.setItem(STORAGE.model,model);$("apiDialog").close();updateApiButton()}
function removeApiSettings(){localStorage.removeItem(STORAGE.api);$("apiKey").value="";updateApiButton();$("apiDialog").close()}
function updateApiButton(){$("apiButton").textContent=localStorage.getItem(STORAGE.api)?"API 연결됨":"API 설정"}
function shuffle(array){const a=[...array];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function drawReferences(){
  const type=$("typeSelect").value;if(!type){state.references=[];renderReferences();return}
  const format=$("formatSelect").value,count=Number($("referenceCount").value),normalOnly=$("normalOnly").checked;
  let candidates=state.db.filter(x=>x.type===type&&(!normalOnly||x.status==="정상"));
  const preferred=format==="auto"?candidates:candidates.filter(x=>x.formatTags.includes(format));
  const first=shuffle(preferred),rest=shuffle(candidates.filter(x=>!first.some(y=>y.id===x.id)));
  const picked=[];for(const row of [...first,...rest]){if(picked.some(x=>x.id===row.id))continue;if(format==="auto"&&picked.length&&picked.every(x=>x.formatTags.join("|")===row.formatTags.join("|"))&&candidates.length>count)continue;picked.push({...row,excluded:false});if(picked.length===count)break}
  if(picked.length<count){for(const row of shuffle(candidates)){if(picked.some(x=>x.id===row.id))continue;picked.push({...row,excluded:false});if(picked.length===count)break}}
  state.references=picked;renderReferences();
}
function renderReferences(){const box=$("referenceList");if(!state.references.length){box.innerHTML='<div class="empty">유형을 선택해 주세요.</div>';return}box.replaceChildren(...state.references.map((row,index)=>{const btn=document.createElement("button");btn.type="button";btn.className=`reference-card${row.excluded?" excluded":""}`;btn.innerHTML=`<img alt="${escapeHtml(sourceText(row))} 문제" loading="lazy"><div><strong>${escapeHtml(sourceText(row))}</strong><p>${escapeHtml(row.prompt.slice(0,115))}</p>${row.formatTags.map(t=>`<span class="tag">${escapeHtml(t)}</span>`).join("")}</div>`;const img=btn.querySelector("img");loadImage(img,row);btn.addEventListener("click",()=>{state.references[index].excluded=!state.references[index].excluded;renderReferences()});return btn}))}
function sourceText(row){const year=String(row.sourceYear||row.year).padStart(2,"0"),month=String(row.month).padStart(2,"0"),num=String(row.number).padStart(2,"0");return `${year} ${month} ${row.grade} 통합과학 ${num}번`}
function loadImage(img,row){const urls=[row.imageUrl,row.fallbackImageUrl].filter(Boolean);let i=0;img.onerror=()=>{i++;if(i<urls.length)img.src=urls[i];else img.style.visibility="hidden"};if(urls.length)img.src=urls[0]}
async function imagePart(row){for(const url of [row.imageUrl,row.fallbackImageUrl].filter(Boolean)){try{const res=await fetch(url);if(!res.ok)continue;const blob=await res.blob();const data=await blobToBase64(blob);return{inlineData:{mimeType:blob.type||"image/png",data}}}catch{}}return null}
function blobToBase64(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(",")[1]);r.onerror=reject;r.readAsDataURL(blob)})}
function referenceText(row){return `출처: ${sourceText(row)}\n유형: ${row.type}\n발문:\n${row.prompt}\n보기:\n${row.view}\n선지:\n${row.choices.map((x,i)=>`${"①②③④⑤"[i]} ${x}`).join("\n")}\n정답: ${row.answer}\n해설:\n${row.explanation}`}
async function generate(){
  const api=localStorage.getItem(STORAGE.api),model=localStorage.getItem(STORAGE.model)||"gemini-3.5-flash",refs=state.references.filter(x=>!x.excluded);
  if(!api){$("apiDialog").showModal();return}if(!$("typeSelect").value){alert("문항 유형을 선택해 주세요.");return}if(refs.length<2){alert("참고 문항을 2개 이상 포함해 주세요.");return}
  state.result=null;$("resultContent").hidden=true;$("resultEmpty").hidden=false;$("reviewDetails").hidden=true;saveRules();$("generateButton").disabled=true;$("progressBox").hidden=false;openTab("generate");
  try{
    progress(12,"1/3 참고 문항 분석","이미지와 원문을 함께 읽어 문항 구조를 분리하고 있습니다.");
    const imageParts=await Promise.all(refs.map(imagePart));
    if(imageParts.some(x=>!x))throw new Error("참고 이미지 로딩 실패. API를 호출하지 않았습니다.");
    const analysis=await callGemini(api,model,[{text:`다음 ${refs.length}개의 통합과학 문항을 분석하라. 새 문항은 아직 만들지 않는다. 공통 개념, 각 문항의 자료 형식, 수치·조건 구조, 난이도 요인, 결합 가능한 요소, 그대로 복제하면 안 되는 요소를 JSON으로 반환하라.\n\n${refs.map(referenceText).join("\n\n---\n\n")}`},...imageParts],analysisSchema());
    progress(48,"2/3 변형 문항 생성","참고 구조를 결합해 새로운 문제와 해설을 만들고 있습니다.");
    const rules=collectRules(),generation=await callGemini(api,model,[{text:`${QUALITY_RULES}\n2028 수능 대비 평가원 문항 1개를 생성하라. 참고 문항을 단순 복제하지 말고 분석된 구조를 새 상황과 새 수치로 재구성하라.\n\n[목표]\n교육과정: 2022 개정 통합과학1·2\n유형: ${$("typeSelect").value}\n문항 번호: ${$("questionNumber").value}\n난이도: ${$("difficulty").value}\n자료 형식: ${$("formatSelect").value}\n추가 지시: ${$("extraPrompt").value||"없음"}\n\n[규칙]\n${Object.values(rules).join("\n\n")}\n\n[참고 문항 분석]\n${JSON.stringify(analysis)}\n\n[참고 원문과 해설]\n${refs.map(referenceText).join("\\n\\n")}\n\n필요한 표는 visual.type=table과 headers/rows로 표현한다. 그래프·모식도·실험 장치·삽화가 필요하면 명세만 쓰지 말고 visual.type=svg로 정하고, 완성된 흑백 평가원 스타일 SVG 전체를 visual.svg에 넣어라. SVG는 viewBox와 명확한 한국어 표기를 포함하고 문제의 수치·기호·축·범례와 정확히 일치해야 한다. script, foreignObject, 외부 이미지·폰트, 이벤트 속성은 금지한다. 시각 자료가 필요 없을 때만 none을 쓴다. JSON 스키마를 지켜라.`},...imageParts],questionSchema());
    const draft=normalizeQuestion(generation); const draftErrors=validateQuestion(draft);
    const draftPng=await prepareFigure(draft);
    progress(78,"3/3 논리 검토·교정","정답을 독립적으로 다시 풀고 조건과 해설을 교정하고 있습니다.");
    const reviewed=await callGemini(api,model,[{text:`${QUALITY_RULES}\n[프로그램 검사] ${draftErrors.join(", ")}\n첨부 이미지는 실제 출력 그림이다. 겹침·누락·본문과의 일치를 검토하라. 아래 생성 문항을 독립적으로 다시 풀어 검토하라. 정답 유일성, 조건 충분성, 각 보기의 참·거짓, 선택지 조합, 수치·단위, 표·그림과 본문의 일치, 2022 개정 통합과학1·2 범위, SVG의 축·눈금·수치·기호·범례 일치, 작성 규칙을 검사하라. 오류가 하나라도 있으면 직접 고쳐 correctedQuestion에 완성본을 넣어라. 오류가 없어도 correctedQuestion에 원문 전체를 그대로 넣어라.\n\n[작성 규칙]\n${Object.values(rules).join("\n\n")}\n\n[생성 문항]\n${JSON.stringify(generation)}`},...(draftPng?[{inlineData:{mimeType:"image/png",data:draftPng.split(",")[1]}}]:[])],reviewSchema());
    const final=normalizeQuestion(reviewed.correctedQuestion);const issues=validateQuestion(final);
    if(!["통과","수정됨"].includes(reviewed.review?.status)||reviewed.review.independentAnswer!==final.answer||issues.length)throw new Error("검토 미통과: "+(issues.join(", ")||"독립 정답 불일치 또는 검토 실패")+" / 자동 추가 결제 없음");
    const figurePng=await prepareFigure(final);
    state.result={...final,figurePng,review:reviewed.review,references:refs.map(sourceText),number:$("questionNumber").value,difficulty:$("difficulty").value,type:$("typeSelect").value};renderResult();progress(100,"완료","검토와 교정이 끝났습니다.");openTab("result");
  }catch(e){console.error(e);progress(0,"생성 실패",e.message);alert(`문항 생성에 실패했습니다.\n${e.message}`)}finally{$("generateButton").disabled=false}
}
async function callGemini(api,model,parts,schema){const url=`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(api)}`;const res=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({contents:[{role:"user",parts}],generationConfig:{temperature:.55,responseMimeType:"application/json",responseSchema:schema}})});const payload=await res.json();if(!res.ok)throw new Error(payload?.error?.message||`Gemini API 오류 ${res.status}`);const text=payload?.candidates?.[0]?.content?.parts?.map(x=>x.text||"").join("");if(!text)throw new Error("Gemini가 응답 내용을 반환하지 않았습니다.");try{return JSON.parse(text)}catch{throw new Error("Gemini 응답을 JSON으로 해석하지 못했습니다.")}}
function analysisSchema(){return{type:"OBJECT",properties:{commonConcept:{type:"STRING"},referenceStructures:{type:"ARRAY",items:{type:"OBJECT",properties:{source:{type:"STRING"},format:{type:"STRING"},logic:{type:"STRING"},difficultyFactors:{type:"ARRAY",items:{type:"STRING"}}},required:["source","format","logic"]}},combinationPlan:{type:"STRING"},avoidCopying:{type:"ARRAY",items:{type:"STRING"}}},required:["commonConcept","referenceStructures","combinationPlan","avoidCopying"]}}
function questionFields(){return{title:{type:"STRING"},prompt:{type:"STRING"},view:{type:"STRING"},choices:{type:"ARRAY",items:{type:"STRING"},minItems:5,maxItems:5},answer:{type:"STRING"},analysis:{type:"STRING"},correctExplanation:{type:"STRING"},wrongExplanation:{type:"STRING"},visual:{type:"OBJECT",properties:{type:{type:"STRING",enum:["none","table","svg"]},headers:{type:"ARRAY",items:{type:"STRING"}},rows:{type:"ARRAY",items:{type:"ARRAY",items:{type:"STRING"}}},svg:{type:"STRING"}},required:["type"]}}}
function questionSchema(){return{type:"OBJECT",properties:questionFields(),required:["title","prompt","view","choices","answer","analysis","correctExplanation","wrongExplanation","visual"]}}
function reviewSchema(){return{type:"OBJECT",properties:{review:{type:"OBJECT",properties:{status:{type:"STRING",enum:["통과","수정됨","생성 실패"]},issues:{type:"ARRAY",items:{type:"STRING"}},changes:{type:"ARRAY",items:{type:"STRING"}},independentAnswer:{type:"STRING"}},required:["status","issues","changes","independentAnswer"]},correctedQuestion:questionSchema()},required:["review","correctedQuestion"]}}
function renderResult(){const r=state.result;if(!r)return;$("resultEmpty").hidden=true;$("resultContent").hidden=false;$("reviewDetails").hidden=false;const visual=r.figurePng?`<figure><img src="${r.figurePng}" alt="문항 그림" style="width:640px;max-width:100%;height:auto"></figure>`:renderVisual(r.visual);$("resultContent").innerHTML=`<h2>${escapeHtml(r.number)}번 답 ${escapeHtml(r.answer)}-${escapeHtml(r.type)}(${escapeHtml(r.difficulty)})</h2><div class="source">${r.references.map(escapeHtml).join(", ")} 참고</div><h3>(문제)</h3><div class="question-block">${formatText(r.prompt)}</div>${visual}${r.view?`<div class="view-box">${formatText(r.view)}</div>`:""}<div class="choice-list">${r.choices.map((x,i)=>`<div>${"①②③④⑤"[i]} ${formatText(x)}</div>`).join("")}</div><div class="solution"><h3>(해설)</h3>${formatText(r.analysis)}<br><br>${formatText(r.correctExplanation)}<p class="wrong-title">[오답 풀이]</p>${formatText(r.wrongExplanation)}</div>`;$("reviewContent").innerHTML=`<p><b>상태:</b> ${escapeHtml(r.review.status)} · <b>독립 풀이 정답:</b> ${escapeHtml(r.review.independentAnswer)}</p><p><b>발견 사항</b><br>${r.review.issues.map(escapeHtml).join("<br>")||"없음"}</p><p><b>수정 사항</b><br>${r.review.changes.map(escapeHtml).join("<br>")||"없음"}</p>`}
function renderVisual(v){if(!v||v.type==="none")return"";if(v.type==="table"&&v.rows?.length)return`<table class="generated-table"><thead><tr>${(v.headers||[]).map(x=>`<th>${formatText(x)}</th>`).join("")}</tr></thead><tbody>${v.rows.map(row=>`<tr>${row.map(x=>`<td>${formatText(x)}</td>`).join("")}</tr>`).join("")}</tbody></table>`;if(v.type==="svg"&&v.svg)return`<div class="generated-visual" role="img" aria-label="문항 시각 자료">${sanitizeSvg(v.svg)}</div>`;return""}
function sanitizeSvg(raw){const doc=new DOMParser().parseFromString(String(raw),"image/svg+xml"),svg=doc.documentElement;if(svg.nodeName.toLowerCase()!=="svg"||doc.querySelector("parsererror"))return"";doc.querySelectorAll("script,foreignObject,iframe,object,embed,image,style,link").forEach(x=>x.remove());doc.querySelectorAll("*").forEach(el=>[...el.attributes].forEach(a=>{const n=a.name.toLowerCase(),v=a.value.trim();if(n.startsWith("on")||n==="href"||n.endsWith(":href")||/url\s*\(/i.test(v))el.removeAttribute(a.name)}));if(!svg.getAttribute("viewBox")){const w=parseFloat(svg.getAttribute("width"))||640,h=parseFloat(svg.getAttribute("height"))||360;svg.setAttribute("viewBox",`0 0 ${w} ${h}`)}svg.removeAttribute("width");svg.removeAttribute("height");return new XMLSerializer().serializeToString(svg)}
function formatText(text){return escapeHtml(text||"").replace(/\n/g,"<br>").replace(/([A-Za-z][A-Za-z0-9()]*)\^([0-9]*[+−-])/g,"$1<sup>$2</sup>").replace(/([A-Za-z)])_([0-9]+)/g,"$1<sub>$2</sub>")}
function escapeHtml(value){return String(value??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
async function legacyCopyResult(all){if(!state.result)return;const source=$("resultContent").cloneNode(true);if(!all)source.querySelector(".solution")?.remove();const html=source.innerHTML,plain=source.innerText;try{await navigator.clipboard.write([new ClipboardItem({"text/html":new Blob([html],{type:"text/html"}),"text/plain":new Blob([plain],{type:"text/plain"})})]);flash(all?$("copyAll"):$("copyQuestion"),"복사됨")}catch{await navigator.clipboard.writeText(plain)}}
function progress(value,title,text){$("progressBar").style.width=`${value}%`;$("progressTitle").textContent=title;$("progressText").textContent=text}
function flash(button,text){const old=button.textContent;button.textContent=text;setTimeout(()=>button.textContent=old,900)}

async function copyResult(all){return copyFinished(all);}
